[2024-08-01 00:51:10,733] 	INFO 	27 	emissions_data.py 	<module>() 	Emissions Data Started
[2024-08-01 00:52:44,778] 	INFO 	99 	emissions_data.py 	<module>() 	Emissions Data Ended
[2024-08-01 01:04:01,144] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-01 01:09:37,942] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-01 01:09:38,642] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-01 01:09:40,044] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-01 01:09:40,044] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-01 01:09:42,436] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-01 01:09:42,436] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-01 01:09:45,145] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-01 01:09:45,971] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-01 01:11:16,047] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-01 01:11:16,047] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-01 01:11:16,191] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,512] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,649] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,787] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,949] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:17,828] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:18,138] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:18,735] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:19,651] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:20,440] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:23,444] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:23,575] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:24,160] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:24,451] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:24,800] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:25,448] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-STKBNB, Address: 0x8b41d72def3867E19f2285B45DA655e24928018F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:26,617] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aDAO-ankrBNB, Address: 0x11C92deD470A50C96d2e5EFfEdc890cd4bd2502e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:27,130] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:28,376] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:29,126] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:33,494] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:12:02,505] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-01 01:12:02,506] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-01 01:12:39,106] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-01 01:12:39,986] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-01 01:45:10,955] 	ERROR 	156 	bribe_data.py 	<module>() 	Error occurred during Bribe Data process. Error: Dataframe is empty
[2024-08-01 01:45:11,581] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-01 01:45:27,513] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-01 01:45:28,099] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-01 01:45:39,635] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-01 01:45:40,224] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-01 01:47:54,716] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-01 01:47:54,716] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-01 01:48:42,144] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-01 01:48:42,144] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-01 01:48:54,169] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
