[2024-08-01 00:51:10,733] 	INFO 	27 	emissions_data.py 	<module>() 	Emissions Data Started
[2024-08-01 00:52:44,778] 	INFO 	99 	emissions_data.py 	<module>() 	Emissions Data Ended
[2024-08-01 01:04:01,144] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-01 01:09:37,942] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-01 01:09:38,642] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-01 01:09:40,044] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-01 01:09:40,044] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-01 01:09:42,436] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-01 01:09:42,436] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-01 01:09:45,145] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-01 01:09:45,971] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-01 01:11:16,047] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-01 01:11:16,047] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-01 01:11:16,191] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,512] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,649] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,787] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,949] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:17,828] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:18,138] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:18,735] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:19,651] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:20,440] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:23,444] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:23,575] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:24,160] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:24,451] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:24,800] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:25,448] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-STKBNB, Address: 0x8b41d72def3867E19f2285B45DA655e24928018F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:26,617] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aDAO-ankrBNB, Address: 0x11C92deD470A50C96d2e5EFfEdc890cd4bd2502e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:27,130] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:28,376] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:29,126] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:33,494] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:12:02,505] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-01 01:12:02,506] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-01 01:12:39,106] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-01 01:12:39,986] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-01 01:45:10,955] 	ERROR 	156 	bribe_data.py 	<module>() 	Error occurred during Bribe Data process. Error: Dataframe is empty
[2024-08-01 01:45:11,581] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-01 01:45:27,513] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-01 01:45:28,099] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-01 01:45:39,635] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-01 01:45:40,224] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-01 01:47:54,716] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-01 01:47:54,716] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-01 01:48:42,144] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-01 01:48:42,144] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-01 01:48:54,169] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-01 06:18:22,484] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-01 06:22:24,905] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-01 06:22:25,522] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-01 06:22:27,590] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-01 06:22:27,590] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-01 06:22:29,636] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-01 06:22:29,636] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-01 06:22:32,378] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-01 06:22:33,142] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-01 06:23:43,572] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-01 06:23:43,572] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-01 06:23:43,857] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:44,298] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:44,522] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:44,729] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:44,914] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:46,245] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:46,730] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:47,593] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:49,117] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:50,324] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:54,796] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:55,004] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:55,953] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:56,376] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:56,856] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:57,896] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-STKBNB, Address: 0x8b41d72def3867E19f2285B45DA655e24928018F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:59,376] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aDAO-ankrBNB, Address: 0x11C92deD470A50C96d2e5EFfEdc890cd4bd2502e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:59,994] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:24:01,917] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:24:02,989] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:24:09,237] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:24:18,530] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-01 06:24:18,530] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-01 06:24:50,536] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-01 06:24:51,343] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-01 07:03:05,566] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-01 07:03:06,145] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-01 07:03:35,820] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-01 07:03:36,393] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-01 07:03:48,555] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-01 07:03:49,091] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-01 07:04:40,712] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: jBRL/BRZ, Address: 0xa0695f78af837f570bcc50f53e58cda300798b65, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:40,867] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: XCAD(old)/USDT, Address: 0x46c69a989dc56747f007acfa4d6bc7c9fa8137bf, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,033] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/PLAY, Address: 0xb8a85b80a12931fe2a1f5db9295fbdae03616e9b, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,200] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: MPX/BNB, Address: 0x51bfc6e47c96d2b8c564b0ddd2c44fc03707cdc7, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,367] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: sfrxETH/FXS, Address: 0x425198ea58ab9cf9001f59c8aeb8c413a6dbe1b1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,515] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: MIX/BNB, Address: 0x0f7d50a2728de6f94b3ac8013031f527572cc9f1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,675] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: PSTAKE/BUSD, Address: 0x67e51f1de32318f3a27265287ed766839a62cf13, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,824] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ankrBNB/BNB, Address: 0x9c9ead6cfd1ed4dd17cd44eb12229364dd541697, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,979] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: lisUSD/USDT, Address: 0x6ce8014488877f91234ef23012193de6bb0009a8, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,128] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ankrBNB/THE, Address: 0x3575155f5b0eada1e4fda5bc84e2c2c7cef1d9f2, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,284] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: jBRL/BNB, Address: 0xf019759f450c8a1c8cfd4e9ecd34e09f72d7fae5, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,472] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: USDT/ERN, Address: 0x3666f5900e50870e2f84b9a7a26a1ec68adea8bb, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,626] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: CSIX/USDT, Address: 0xce7c38ece02b55070208b2e070585ea5321748e1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,784] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ankrBNB/BNB, Address: 0xfa0429a7eab25ec8d31e247e725afd931cf6bdfe, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,932] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: NGL/USDT, Address: 0xd949476184b9c94ed2130e8175d4139654ce2339, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:43,096] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BETS/BNB, Address: 0x21f60af65ba9a20c3320b6938aaa60237f6beea8, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:05:20,342] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-01 07:05:20,342] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-01 07:06:27,042] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-01 07:06:27,042] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-01 07:06:48,014] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-01 12:24:41,770] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-01 12:28:55,080] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-01 12:28:55,899] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-01 12:28:57,772] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-01 12:28:57,772] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-01 12:28:59,206] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-01 12:28:59,206] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-01 12:29:01,919] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-01 12:29:02,837] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-01 12:30:19,761] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-01 12:30:19,761] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-01 12:30:19,870] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:20,093] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:20,241] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:20,348] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:20,474] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:21,282] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:21,546] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:22,037] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:22,616] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:23,199] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:25,628] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:25,767] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:26,232] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:26,458] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:26,695] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:28,091] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aDAO-ankrBNB, Address: 0x11C92deD470A50C96d2e5EFfEdc890cd4bd2502e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:28,419] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:29,419] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:29,998] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:33,559] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:39,764] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-01 12:30:39,764] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-01 12:31:12,931] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-01 12:31:13,885] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-01 12:55:43,695] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-01 12:55:44,388] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-01 12:56:03,488] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-01 12:56:04,153] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-01 12:56:14,004] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-01 12:56:14,669] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-01 12:58:18,118] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-01 12:58:18,118] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-01 12:58:53,608] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-01 12:58:53,608] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-01 12:59:14,413] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-01 18:16:51,007] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-01 18:20:21,544] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-01 18:20:22,211] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-01 18:20:24,010] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-01 18:20:24,010] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-01 18:20:26,236] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-01 18:20:26,237] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-01 18:20:29,192] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-01 18:20:30,047] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-01 18:21:23,936] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-HAY/ankrBNB, Address: 0xC6dB38F34DA75393E9aac841c08104348997D509, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,104] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-FRAX/WBNB, Address: 0xc7419EBbc4b259C50D7Eeaba49940688A5d52Afa, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,271] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/MIX, Address: 0xC8c8148Fc304503941DfFFe0b28211472597aB74, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,429] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/DEUS, Address: 0xC8Da40f8A354530F04CE2dDe98Ebc2960a9eA449, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,591] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XRP/WBNB, Address: 0xC9688a1e9dBE45F253CC77cB9726A11b323bFD54, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,748] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FITFI/BUSD, Address: 0xcAe2C0d6937671490D3bcE4C21d57fF313f407Eb, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,932] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-fBOMB/WBNB, Address: 0xCcDEdaC1973b6d2542fB1b7EcE843b81A9ee7070, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,087] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-CSIX/USDT, Address: 0xCE7C38ECe02b55070208b2e070585eA5321748e1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,251] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-qTHE/THE, Address: 0xCEd2490a69aeD204e7A10e4Aa10DdDce5224287D, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,417] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/LIQ, Address: 0xD27F175c12C9d147ff1be4844856F224fD6223C4, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,573] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/WBNB, Address: 0xD328D129E46f9B978416599913102e8CD64593F3, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,734] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-FRAX/sFRAX, Address: 0xD46Da49357a3c9da115b3bf20B31b2cf3e5dE58B, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,893] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/FITFI, Address: 0xD523AC2609c3A56f945242CC239e9F47c018bf6b, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,049] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/BUSD, Address: 0xD5B7877cD8056f38bB37FaDb63FE698E406F3870, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,216] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-FRAX/FXS, Address: 0xd6C883ABA697b33110e42077D28361aa3E48f26A, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,391] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-UNW/THE, Address: 0xd714206a7D63F5a2d613064815995E9CC7061988, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,557] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-NGL/USDT, Address: 0xD949476184B9c94Ed2130E8175D4139654CE2339, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,726] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-HAY/USDC, Address: 0xD9937a059D2FCAb6cB0C11Da71cc91F7b33A3870, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,932] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BNBx/ETH, Address: 0xd9BC6271abBE5dd01731B1b9aC2C1Cb0ea5Be246, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,089] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-XCAD/BTCB OLD, Address: 0xd9F7096625B65Ac37c09d05c1c4548edfcCe9fBE, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,262] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FITFI/WBNB, Address: 0xd9f88F54a73B37463fb8F15ece98e0D1DcdCAAB6, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,420] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XCAD/THE, Address: 0xDA2E32203EEe658e0E9b9E1b766ac1ceDb88d1f1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,576] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/RDNT, Address: 0xda57e73e5A2fA00C5c6B660454c1950DCB03E958, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,734] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/dXCAD, Address: 0xDA5edbE3f254046cD8CABeC6758E0B1122B52D6e, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,901] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/THE, Address: 0xdAaC487bB3a411cB9251794bb7c7B04cb6d1aB26, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,065] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/BUSD, Address: 0xDC17b8899D8084E64913BD508bb13BfC2696dEBB, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,217] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-PION/WBNB, Address: 0xDC1e387fC2697F3737EE197712BfeF9e1101ccd5, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,381] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DEI/BUSD, Address: 0xDC2b0436E63bD8654aEA52d1aCD3Ae4F9716A6F4, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,527] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/THE, Address: 0xdC81698F98e275785741F96961f246368FDd5866, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,684] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DUSD/WBNB, Address: 0xdd0118F593c91ef5FA40C34d5687654C215C3D98, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,843] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETS Alpha/BUSD, Address: 0xde34Df68795f0D2b07F64285Ba83601889A6995C, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,003] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MULTI/BUSD, Address: 0xdE4Cc4446205d1138EcAa48B2CB22b8e06E69BD4, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,175] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/PRIMAL, Address: 0xde72DD50Dd0ca9C8c48b04F74c5246B5545969D0, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,333] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/LIQ, Address: 0xdf26702B1A510bc6860b2a1DF11219f216b91445, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,491] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-CHAM/BUSD, Address: 0xDf63A43aEFb5c1Aa4040a3a121d2a8C00EeBE7d8, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,653] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DAI/MAI, Address: 0xe03e9EcC7d4C45c6985bfB909D9Bb3ACa5Ef18c0, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,819] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XCAD/BUSD OLD, Address: 0xe200B5B3F08d1254d05d8797FFA1f99730C0025c, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,982] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/multiBTC, Address: 0xE2256f71F3Df4765A3602db66747eA87a71057b5, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:30,135] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/XCAD OLD, Address: 0xe2d25A87e97a1016c35F736Ea77A4d6Bd1919E74, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:44,397] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-01 18:21:44,397] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-01 18:21:44,617] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:45,026] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:45,243] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:45,445] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:45,656] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:46,874] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:47,304] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:48,114] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:49,213] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:50,275] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:54,366] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:54,578] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:55,386] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:55,779] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:56,168] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:58,414] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aDAO-ankrBNB, Address: 0x11C92deD470A50C96d2e5EFfEdc890cd4bd2502e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:58,991] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:22:00,611] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:22:01,672] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:22:07,441] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:22:14,243] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-01 18:22:14,243] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-01 18:22:42,809] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-01 18:22:43,680] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-01 18:58:48,633] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-01 18:58:49,320] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-01 18:59:01,228] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-01 18:59:01,864] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-01 18:59:11,869] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-01 18:59:12,499] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-01 19:01:55,523] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-01 19:01:55,523] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-01 19:03:08,968] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-01 19:03:08,968] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-01 19:03:29,240] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
