[2023-08-01 00:39:39,915] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-01 00:39:43,070] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-01 00:39:43,070] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-01 00:39:46,385] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-01 00:39:46,385] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-01 00:39:48,281] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-01 00:39:49,384] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-01 00:41:04,382] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-01 00:41:04,382] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-01 00:41:33,282] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-01 00:41:33,283] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-01 00:41:44,799] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-01 00:41:45,835] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-01 00:51:58,550] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-01 00:51:59,275] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-01 00:52:11,152] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-01 01:00:46,780] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 01:02:55,057] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 01:14:09,909] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-01 01:19:13,109] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-01 02:04:54,115] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-01 02:04:57,722] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-01 02:04:57,722] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-01 02:05:01,279] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-01 02:05:01,279] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-01 02:05:03,890] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-01 02:05:05,196] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-01 02:06:12,513] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-01 02:06:12,514] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-01 02:06:36,872] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-01 02:06:36,872] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-01 02:06:51,411] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-01 02:06:52,592] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-01 02:12:07,813] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-01 02:12:08,672] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-01 02:12:17,945] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-01 02:33:41,762] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 02:37:38,630] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 03:11:24,139] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 03:13:27,012] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 03:14:16,985] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-01 03:23:33,520] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-01 04:12:30,674] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 04:14:30,537] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 04:15:43,982] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-01 04:20:33,201] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-01 05:09:56,255] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 05:13:17,466] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 06:14:54,304] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 06:18:29,744] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 07:10:37,642] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 07:12:51,160] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 08:08:25,473] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-01 08:08:27,964] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-01 08:08:27,964] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-01 08:08:30,009] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-01 08:08:30,009] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-01 08:08:32,916] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-01 08:08:34,096] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-01 08:09:36,917] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-01 08:09:36,917] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-01 08:10:12,880] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-01 08:10:12,880] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-01 08:10:25,830] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-01 08:10:26,755] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-01 08:15:00,123] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-01 08:15:00,759] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-01 08:15:06,918] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-01 08:16:47,194] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-01 08:25:17,084] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-01 09:10:22,876] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 09:12:16,616] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 09:13:14,497] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-01 09:21:27,966] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-01 10:11:15,335] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 10:13:22,911] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 11:03:49,701] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-01 11:03:52,502] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-01 11:03:52,503] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-01 11:03:54,817] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-01 11:03:54,817] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-01 11:03:57,070] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-01 11:03:58,410] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-01 11:05:12,702] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-01 11:05:12,703] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-01 11:05:38,507] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-01 11:05:38,507] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-01 11:05:55,464] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-01 11:05:56,612] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-01 11:10:38,880] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-01 11:10:39,766] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-01 11:10:50,791] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-01 12:11:33,889] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-01 12:11:37,262] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-01 12:11:37,262] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-01 12:11:40,472] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-01 12:11:40,472] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-01 12:11:42,160] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-01 12:11:43,927] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-01 12:13:04,883] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-01 12:13:04,883] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-01 12:13:31,197] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-01 12:13:31,197] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-01 12:13:51,647] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-01 12:13:53,098] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-01 12:19:15,738] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-01 12:19:16,771] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-01 12:19:29,075] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-01 12:21:09,271] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 12:23:18,401] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 12:26:58,681] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-01 12:35:11,733] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-01 13:13:25,962] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 13:15:45,548] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 13:16:43,286] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-01 13:21:44,806] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-01 14:04:53,990] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-01 14:04:57,664] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-01 14:04:57,664] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-01 14:05:00,249] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-01 14:05:00,250] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-01 14:05:02,539] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-01 14:05:03,676] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-01 14:06:16,673] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-01 14:06:16,673] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-01 14:06:35,871] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-01 14:06:35,871] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-01 14:06:50,201] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-01 14:06:51,138] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-01 14:11:49,465] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-01 14:11:50,154] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-01 14:12:00,289] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-01 15:10:47,392] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 15:11:20,617] 	ERROR 	122 	id_data_v2.py 	<module>() 	Error occurred during ID Data process. Error: {'code': 0, 'message': "we can't execute this request"}
[2023-08-01 15:13:33,160] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-01 15:18:26,700] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-01 16:13:10,088] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 16:17:09,531] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 17:08:54,520] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 17:11:11,897] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 18:12:47,004] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 18:15:06,974] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 18:16:13,082] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-01 18:25:37,158] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-01 19:03:29,280] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-01 19:03:32,758] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-01 19:03:32,758] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-01 19:03:36,922] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-01 19:03:36,922] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-01 19:03:39,867] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-01 19:03:41,041] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-01 19:05:11,196] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-01 19:05:11,197] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-01 19:05:34,455] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-01 19:05:34,455] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-01 19:05:52,115] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-01 19:05:53,199] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-01 19:11:43,155] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-01 19:11:43,971] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-01 19:12:03,018] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-01 20:11:01,322] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 20:13:05,417] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 21:04:32,564] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-01 21:04:34,786] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-01 21:04:34,786] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-01 21:04:36,961] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-01 21:04:36,961] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-01 21:04:39,696] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-01 21:04:40,954] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-01 21:05:53,580] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-01 21:05:53,580] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-01 21:06:18,684] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-01 21:06:18,684] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-01 21:06:34,071] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-01 21:06:35,250] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-01 21:12:11,515] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-01 21:12:12,365] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-01 21:12:26,695] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-01 22:09:16,966] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-01 22:11:47,886] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-01 23:04:21,014] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-01 23:04:26,379] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-01 23:04:26,379] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-01 23:04:30,369] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-01 23:04:30,369] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-01 23:04:33,119] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-01 23:04:34,274] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-01 23:05:47,947] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-01 23:05:47,947] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-01 23:06:09,143] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-01 23:06:09,143] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-01 23:06:18,332] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-01 23:06:19,403] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-01 23:11:10,375] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-01 23:11:11,155] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-01 23:11:16,802] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-01 23:12:50,504] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-01 23:17:44,213] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-02 00:35:00,201] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-02 00:35:03,658] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-02 00:35:03,658] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-02 00:35:06,219] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-02 00:35:06,219] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-02 00:35:09,624] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-02 00:35:11,148] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-02 00:36:30,705] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-02 00:36:30,706] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-02 00:36:54,561] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-02 00:36:54,561] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-02 00:39:27,761] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-02 00:39:29,081] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-02 00:44:23,389] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-02 00:44:24,342] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-02 00:44:38,823] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-02 00:53:29,018] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 00:57:20,184] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 01:05:38,982] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-02 01:10:28,164] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-02 01:55:17,883] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 01:57:14,883] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 02:22:42,178] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 02:24:50,947] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 03:10:28,178] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 03:12:42,427] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 04:11:59,393] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 04:14:01,593] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 04:15:18,469] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-02 04:20:19,197] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-02 05:09:51,262] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 05:11:55,878] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 06:13:27,659] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 06:17:00,199] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 07:09:33,829] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 07:11:39,170] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 08:12:53,016] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 08:14:52,002] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 08:16:13,017] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-02 08:20:53,534] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-02 09:10:11,087] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 09:12:10,083] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 10:11:20,095] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 10:13:21,464] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 11:08:29,734] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 11:10:45,636] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 12:11:01,298] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-02 12:11:04,977] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-02 12:11:04,978] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-02 12:11:07,155] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-02 12:11:07,156] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-02 12:11:09,958] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-02 12:11:11,212] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-02 12:13:12,754] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-02 12:13:12,755] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-02 12:13:41,134] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-02 12:13:41,134] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-02 12:13:51,008] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-02 12:13:52,030] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-02 12:19:23,521] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-02 12:19:24,267] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-02 12:19:41,364] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-02 12:26:14,716] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-02 12:31:57,132] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-02 13:13:38,015] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 13:17:18,172] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 14:04:39,934] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-02 14:04:43,821] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-02 14:04:43,821] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-02 14:04:46,920] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-02 14:04:46,920] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-02 14:04:59,497] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-02 14:05:00,717] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-02 14:06:33,003] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-02 14:06:33,003] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-02 14:07:02,004] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-02 14:07:02,004] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-02 14:07:14,851] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-02 14:07:15,765] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-02 14:13:06,972] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-02 14:13:07,628] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-02 14:13:13,028] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-02 15:09:52,956] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 15:12:14,325] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 16:07:34,588] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-02 16:07:36,728] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-02 16:07:36,728] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-02 16:07:39,045] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-02 16:07:39,045] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-02 16:07:41,009] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-02 16:07:42,809] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-02 16:08:52,987] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-02 16:08:52,987] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-02 16:09:14,887] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-02 16:09:14,887] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-02 16:09:29,760] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-02 16:09:30,902] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-02 16:15:13,801] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-02 16:15:14,708] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-02 16:15:21,429] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-02 16:17:16,538] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-02 16:27:06,264] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-02 17:09:06,174] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 17:12:48,818] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 18:12:23,435] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 18:14:37,821] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 18:15:48,560] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-02 18:21:41,345] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-02 19:08:16,797] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 19:10:43,559] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 20:06:12,472] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-02 20:06:15,511] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-02 20:06:15,511] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-02 20:06:19,273] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-02 20:06:19,274] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-02 20:06:21,089] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-02 20:06:22,073] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-02 20:07:32,375] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-02 20:07:32,375] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-02 20:07:53,872] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-02 20:07:53,872] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-02 20:08:06,822] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-02 20:08:07,779] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-02 20:14:16,512] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-02 20:14:17,189] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-02 20:14:23,432] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-02 21:08:52,315] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 21:11:00,708] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 22:08:58,790] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 22:11:21,169] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-02 23:09:45,048] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-02 23:11:58,915] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 00:35:27,062] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-03 00:35:29,998] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-03 00:35:29,998] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-03 00:35:32,415] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-03 00:35:32,415] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-03 00:35:35,504] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-03 00:35:36,764] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-03 00:36:53,020] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-03 00:36:53,020] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-03 00:37:18,051] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-03 00:37:18,051] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-03 00:37:29,757] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-03 00:37:30,765] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-03 00:42:32,995] 	ERROR 	152 	bribe_data.py 	<module>() 	Error occurred during Bribe Data process. Error: 'address'
[2023-08-03 00:42:33,720] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-03 00:42:42,974] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-03 00:45:09,910] 	INFO 	27 	emissions_data.py 	<module>() 	Emissions Data Started
[2023-08-03 00:46:42,604] 	INFO 	99 	emissions_data.py 	<module>() 	Emissions Data Ended
[2023-08-03 00:56:51,418] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 00:59:11,315] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 01:07:54,661] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-03 01:13:48,811] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-03 01:58:34,007] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 02:01:00,588] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 02:28:11,831] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 02:30:48,478] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 03:10:30,749] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 03:13:05,939] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 04:12:20,499] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 04:14:50,936] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 05:09:36,432] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 05:11:53,872] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 06:13:14,285] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 06:15:30,914] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 06:16:54,587] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-03 06:22:14,447] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-03 07:09:42,883] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 07:11:45,289] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 07:12:18,354] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-03 07:17:32,984] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-03 08:08:11,357] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-03 08:08:13,826] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-03 08:08:13,827] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-03 08:08:15,773] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-03 08:08:15,773] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-03 08:08:17,340] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-03 08:08:18,447] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-03 08:09:27,666] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-03 08:09:27,666] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-03 08:09:52,881] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-03 08:09:52,881] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-03 08:10:04,781] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-03 08:10:05,756] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-03 08:16:01,112] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-03 08:16:01,823] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-03 08:16:13,538] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-03 09:05:17,246] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-03 09:05:21,444] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-03 09:05:21,444] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-03 09:05:24,924] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-03 09:05:24,924] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-03 09:05:27,709] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-03 09:05:28,915] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-03 09:06:49,243] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-03 09:06:49,243] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-03 09:07:18,704] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-03 09:07:18,705] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-03 09:07:35,596] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-03 09:07:36,639] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-03 09:13:10,053] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-03 09:13:10,856] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-03 09:13:20,381] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-03 10:10:40,661] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 10:13:01,257] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 11:08:44,124] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 11:10:56,378] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 12:20:41,206] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 12:22:48,823] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 12:27:20,628] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-03 12:33:25,164] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-03 13:13:22,865] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 13:16:03,230] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 14:09:33,832] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 14:12:13,648] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 15:10:34,932] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 15:12:55,844] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 16:12:06,272] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 16:14:36,940] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 16:15:47,611] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-03 16:21:53,529] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-03 17:04:09,975] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-03 17:04:12,850] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-03 17:04:12,850] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-03 17:04:14,792] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-03 17:04:14,792] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-03 17:04:17,474] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-03 17:04:18,631] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-03 17:05:33,569] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-03 17:05:33,570] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-03 17:05:56,465] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-03 17:05:56,466] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-03 17:06:17,211] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-03 17:06:18,202] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-03 17:12:16,327] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-03 17:12:17,018] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-03 17:12:29,126] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-03 18:12:32,289] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-03 18:15:17,864] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-03 18:15:51,285] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-03 18:21:47,711] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-03 19:03:24,843] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-03 19:03:28,013] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-03 19:03:28,013] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-03 19:03:29,952] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-03 19:03:29,952] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-03 19:03:32,593] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-03 19:03:34,072] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-03 19:04:48,220] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-03 19:04:48,220] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-03 19:05:13,818] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-03 19:05:13,818] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-03 19:05:34,883] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-03 19:05:36,214] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-03 19:11:41,735] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-03 19:11:42,627] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-03 19:11:48,654] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-03 20:06:22,702] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-03 20:06:25,671] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-03 20:06:25,671] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-03 20:06:29,076] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-03 20:06:29,076] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-03 20:06:31,067] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-03 20:06:32,308] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-03 20:07:46,522] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-03 20:07:46,522] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-03 20:08:10,477] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-03 20:08:10,477] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-03 20:08:30,557] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-03 20:08:31,770] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-03 20:14:01,237] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-03 20:14:02,150] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-03 20:14:08,442] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-03 21:04:09,424] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-03 21:04:11,888] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-03 21:04:11,888] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-03 21:04:13,731] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-03 21:04:13,731] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-03 21:04:17,067] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-03 21:04:18,489] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-03 21:05:28,501] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-03 21:05:28,501] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-03 21:05:58,776] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-03 21:05:58,777] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-03 21:06:18,046] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-03 21:06:19,294] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-03 21:11:55,716] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-03 21:11:56,558] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-03 21:12:02,676] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-03 22:04:25,845] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-03 22:04:28,905] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-03 22:04:28,905] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-03 22:04:30,909] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-03 22:04:30,909] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-03 22:04:33,386] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-03 22:04:34,425] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-03 22:05:44,671] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-03 22:05:44,672] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-03 22:06:04,892] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-03 22:06:04,893] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-03 22:06:11,557] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-03 22:06:12,567] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-03 22:12:27,984] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-03 22:12:28,723] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-03 22:12:33,370] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-03 23:05:11,010] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-03 23:05:13,297] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-03 23:05:13,297] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-03 23:05:14,822] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-03 23:05:14,822] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-03 23:05:16,776] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-03 23:05:18,116] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-03 23:06:23,803] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-03 23:06:23,803] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-03 23:06:53,182] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-03 23:06:53,182] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-03 23:07:02,370] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-03 23:07:03,434] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-03 23:12:34,466] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-03 23:12:35,180] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-03 23:12:41,386] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-04 00:34:54,289] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-04 00:34:56,653] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-04 00:34:56,653] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-04 00:34:59,108] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-04 00:34:59,108] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-04 00:35:01,247] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-04 00:35:02,318] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-04 00:36:11,680] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-04 00:36:11,680] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-04 00:36:38,755] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-04 00:36:38,755] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-04 00:36:52,687] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-04 00:36:53,590] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-04 00:42:56,061] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-04 00:42:56,719] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-04 00:43:04,191] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-04 00:57:10,401] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 01:01:14,204] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 01:10:10,518] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-04 01:19:32,717] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-04 02:00:04,467] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 02:02:24,838] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 02:22:51,999] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-04 02:22:54,568] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-04 02:22:54,568] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-04 02:22:56,571] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-04 02:22:56,571] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-04 02:22:58,781] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-04 02:22:59,838] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-04 02:24:19,522] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-04 02:24:19,522] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-04 02:24:52,791] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-04 02:24:52,791] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-04 02:25:07,104] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-04 02:25:08,037] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-04 02:31:25,845] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-04 02:31:26,503] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-04 02:31:34,243] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-04 03:10:25,248] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 03:12:43,472] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 04:12:03,233] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 04:14:27,551] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 04:15:19,412] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-04 04:25:08,409] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-04 05:09:44,085] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 05:12:07,215] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 06:13:20,141] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 06:15:37,900] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 06:16:49,293] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-04 06:26:05,035] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-04 07:09:20,497] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 07:12:42,292] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 08:12:46,578] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 08:14:56,481] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 08:16:14,871] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-04 08:24:29,869] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-04 09:10:07,012] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 09:12:22,278] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 10:06:03,315] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-04 10:06:05,545] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-04 10:06:05,545] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-04 10:06:07,578] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-04 10:06:07,578] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-04 10:06:09,641] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-04 10:06:10,742] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-04 10:07:13,055] 	INFO 	107 	pair_data.py 	<module>() 	Pair Data Ended
[2023-08-04 10:07:13,055] 	INFO 	123 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-04 10:07:35,785] 	INFO 	190 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-04 10:07:35,785] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-04 10:07:52,710] 	INFO 	227 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-04 10:07:53,687] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-04 10:13:14,926] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-04 10:13:15,646] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-04 10:13:25,374] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-04 11:08:35,096] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 11:10:49,780] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 12:19:34,455] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 12:21:44,205] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 12:25:31,103] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-04 12:31:01,309] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-04 13:12:21,617] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 13:14:48,360] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 13:15:44,799] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-04 13:21:13,635] 	ERROR 	141 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-08-04 14:09:21,135] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 14:11:47,830] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 15:10:17,937] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 15:12:43,578] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 16:12:29,115] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 16:14:51,159] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 16:16:27,321] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-04 16:22:14,439] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-04 17:08:50,608] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 17:11:18,129] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 18:12:35,270] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 18:15:18,291] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 18:16:11,320] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-04 18:21:50,979] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-04 19:08:05,453] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 19:11:55,221] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 20:10:25,829] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 20:12:40,431] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 21:03:42,563] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 21:06:04,751] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 21:06:05,480] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-04 21:06:08,346] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-04 21:06:08,347] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-04 21:06:10,422] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-04 21:06:10,422] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-04 21:06:12,701] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-04 21:06:13,613] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-04 21:07:10,543] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-04 21:07:10,543] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-04 21:07:37,123] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-04 21:07:37,123] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-04 21:07:50,325] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-04 21:07:51,280] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-04 21:13:46,182] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-04 21:13:46,923] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-04 21:13:54,730] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-04 22:04:28,239] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-04 22:06:40,303] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-04 22:06:41,137] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-04 22:06:45,714] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-04 22:06:45,714] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-04 22:06:48,325] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-04 22:06:48,325] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-04 22:06:50,313] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-04 22:06:51,514] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-04 22:07:53,442] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-04 22:07:53,443] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-04 22:08:16,826] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-04 22:08:16,826] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-04 22:08:29,166] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-04 22:08:30,464] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-04 22:13:59,538] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-04 22:14:00,447] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-04 22:14:07,566] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-04 23:11:52,292] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-04 23:17:25,772] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-05 00:34:14,742] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 00:38:00,384] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 00:38:01,262] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 00:38:06,307] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 00:38:06,307] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 00:38:09,218] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 00:38:09,218] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 00:38:12,147] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 00:38:13,244] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 00:39:15,377] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 00:39:15,377] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 00:39:44,069] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 00:39:44,069] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 00:40:01,249] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 00:40:02,383] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 00:49:41,151] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 00:49:41,962] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 00:50:03,251] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 01:06:21,672] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-05 01:12:09,087] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-05 01:52:00,896] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 01:54:15,695] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 01:54:16,506] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 01:54:19,909] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 01:54:19,909] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 01:54:22,155] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 01:54:22,156] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 01:54:23,858] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 01:54:24,814] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 01:55:21,172] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 01:55:21,173] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 01:55:46,427] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 01:55:46,427] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 01:56:17,973] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 01:56:19,009] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 02:02:07,142] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 02:02:07,889] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 02:02:38,827] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 02:19:53,225] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 02:22:12,561] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 02:22:13,359] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 02:22:15,935] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 02:22:15,935] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 02:22:18,111] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 02:22:18,112] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 02:22:19,969] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 02:22:20,919] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 02:23:18,813] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 02:23:18,814] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 02:23:43,938] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 02:23:43,938] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 02:23:57,192] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 02:23:58,201] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 02:29:56,594] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 02:29:57,318] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 02:30:09,872] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 03:06:48,112] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 03:09:09,210] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 03:09:10,120] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 03:09:13,054] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 03:09:13,054] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 03:09:15,803] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 03:09:15,804] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 03:09:17,509] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 03:09:18,681] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 03:10:19,542] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 03:10:19,542] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 03:10:47,843] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 03:10:47,844] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 03:10:59,617] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 03:11:00,800] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 03:16:35,705] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 03:16:36,582] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 03:16:53,254] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 04:14:31,621] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-05 04:19:41,232] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-05 05:04:27,006] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 05:06:28,025] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 05:06:28,810] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 05:06:31,104] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 05:06:31,104] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 05:06:33,298] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 05:06:33,298] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 05:06:35,248] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 05:06:36,196] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 05:07:33,820] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 05:07:33,821] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 05:07:52,593] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 05:07:52,593] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 05:08:05,902] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 05:08:06,892] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 05:13:12,067] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 05:13:12,754] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 05:13:25,450] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 06:07:27,871] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 06:11:13,289] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 06:11:14,176] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 06:11:17,218] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 06:11:17,219] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 06:11:19,008] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 06:11:19,009] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 06:11:20,746] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 06:11:21,885] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 06:12:25,846] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 06:12:25,846] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 06:12:48,861] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 06:12:48,862] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 06:13:03,459] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 06:13:04,657] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 06:22:55,204] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 06:22:56,084] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 06:23:16,585] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 07:03:35,909] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 07:05:52,386] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 07:05:53,156] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 07:05:55,687] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 07:05:55,687] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 07:05:57,681] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 07:05:57,681] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 07:05:59,712] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 07:06:00,731] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 07:06:58,383] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 07:06:58,384] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 07:07:19,934] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 07:07:19,934] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 07:07:39,858] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 07:07:40,948] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 07:13:19,407] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 07:13:20,209] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 07:13:25,602] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 08:14:34,857] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-05 08:19:15,489] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-05 09:04:32,300] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 09:06:37,636] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 09:06:38,406] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 09:06:40,900] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 09:06:40,900] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 09:06:43,087] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 09:06:43,088] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 09:06:46,502] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 09:06:47,407] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 09:07:44,814] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 09:07:44,815] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 09:08:06,963] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 09:08:06,963] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 09:08:16,091] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 09:08:16,988] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 09:13:58,182] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 09:13:58,833] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 09:14:07,324] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 10:12:05,175] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-05 10:17:15,843] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-05 11:03:23,435] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 11:05:27,635] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 11:05:28,638] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 11:05:33,704] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 11:05:33,704] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 11:05:37,199] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 11:05:37,199] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 11:05:40,618] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 11:05:41,816] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 11:06:45,104] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 11:06:45,104] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 11:07:11,479] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 11:07:11,479] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 11:07:23,065] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 11:07:24,294] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 11:12:22,580] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 11:12:23,492] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 11:12:39,441] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 12:09:53,898] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 12:13:44,772] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 12:13:45,622] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 12:13:48,478] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 12:13:48,478] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 12:13:50,538] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 12:13:50,539] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 12:14:00,252] 	ERROR 	163 	day_data.py 	<module>() 	Error occurred during Day Data Combined process. Error: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}
[2023-08-05 12:14:01,276] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 12:15:01,815] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 12:15:01,815] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 12:15:25,595] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 12:15:25,596] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 12:15:37,915] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 12:15:38,992] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 12:24:48,866] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 12:24:49,635] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 12:25:09,524] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 13:05:23,111] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 13:07:45,044] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 13:07:45,761] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 13:07:50,775] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 13:07:50,776] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 13:07:54,633] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 13:07:54,633] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 13:07:57,059] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 13:07:57,977] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 13:09:07,217] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 13:09:07,217] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 13:09:33,269] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 13:09:33,269] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 13:09:51,871] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 13:09:52,821] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 13:15:45,018] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 13:15:45,724] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 13:15:51,912] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 14:03:24,403] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 14:05:34,943] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 14:05:35,738] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 14:05:40,531] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 14:05:40,531] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 14:05:43,348] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 14:05:43,349] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 14:05:45,726] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 14:05:46,679] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 14:06:44,027] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 14:06:44,027] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 14:07:06,243] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 14:07:06,243] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 14:07:19,235] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 14:07:20,230] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 14:12:42,864] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 14:12:43,631] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 14:12:48,597] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 15:04:16,965] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 15:06:54,078] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 15:06:54,916] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 15:06:58,919] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 15:06:58,919] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 15:07:01,005] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 15:07:01,005] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 15:07:03,615] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 15:07:04,729] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 15:08:12,981] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 15:08:12,981] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 15:08:38,955] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 15:08:38,956] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 15:09:02,367] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 15:09:03,581] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 15:15:14,155] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 15:15:15,093] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 15:15:21,624] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 16:15:13,245] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-05 16:20:41,885] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-05 17:03:36,716] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 17:05:43,614] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 17:05:44,516] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 17:05:47,878] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 17:05:47,878] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 17:05:50,299] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 17:05:50,299] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 17:05:52,870] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 17:05:54,090] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 17:06:55,755] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 17:06:55,756] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 17:07:23,608] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 17:07:23,609] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 17:07:34,386] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 17:07:35,615] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 17:12:47,031] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 17:12:47,860] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 17:12:55,203] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 18:06:33,130] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 18:08:44,451] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 18:08:45,239] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 18:08:48,355] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 18:08:48,356] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 18:08:50,195] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 18:08:50,195] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 18:08:52,806] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 18:08:53,768] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 18:09:50,257] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 18:09:50,257] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 18:10:12,397] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 18:10:12,397] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 18:10:26,393] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 18:10:27,398] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 18:15:58,602] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 18:15:59,348] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 18:16:06,970] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 19:02:46,340] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 19:04:54,636] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 19:04:55,512] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 19:04:58,185] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 19:04:58,185] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 19:04:59,979] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 19:04:59,979] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 19:05:02,225] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 19:05:03,205] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 19:05:58,663] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 19:05:58,663] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 19:06:24,096] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 19:06:24,096] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 19:06:37,598] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 19:06:38,624] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 19:11:56,550] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 19:11:57,261] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 19:12:05,630] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 20:04:15,609] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 20:06:27,097] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 20:06:27,849] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 20:06:33,458] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 20:06:33,458] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 20:06:35,711] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 20:06:35,711] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 20:06:37,981] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 20:06:38,866] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 20:07:38,161] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 20:07:38,162] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 20:08:06,880] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 20:08:06,881] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 20:08:23,540] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 20:08:24,463] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 20:13:52,663] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 20:13:53,306] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 20:13:58,326] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 21:03:24,919] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 21:05:48,050] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 21:05:48,848] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 21:05:51,478] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 21:05:51,478] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 21:05:53,421] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 21:05:53,421] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 21:05:55,272] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 21:05:56,166] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 21:06:57,717] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 21:06:57,717] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 21:07:22,502] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 21:07:22,503] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 21:07:40,662] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 21:07:41,633] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 21:13:01,904] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 21:13:02,596] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 21:13:10,389] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 22:03:20,308] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 22:05:29,489] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 22:05:30,321] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 22:05:33,298] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 22:05:33,298] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 22:05:35,868] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 22:05:35,868] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 22:05:37,914] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 22:05:39,046] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 22:06:42,357] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 22:06:42,357] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 22:07:11,436] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 22:07:11,436] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 22:07:26,473] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 22:07:27,653] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 22:12:32,230] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 22:12:33,101] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 22:12:41,117] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-05 23:04:26,831] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-05 23:06:35,254] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-05 23:06:36,166] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-05 23:06:40,397] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-05 23:06:40,397] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-05 23:06:42,811] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-05 23:06:42,811] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-05 23:06:44,826] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-05 23:06:45,983] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-05 23:07:49,735] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-05 23:07:49,736] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-05 23:08:16,259] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-05 23:08:16,259] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-05 23:08:34,551] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-05 23:08:35,756] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-05 23:13:59,755] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-05 23:14:00,601] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-05 23:14:10,159] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 00:31:55,688] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 00:34:10,760] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 00:34:11,831] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 00:34:16,831] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 00:34:16,831] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 00:34:19,516] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 00:34:19,516] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 00:34:21,647] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 00:34:22,712] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 00:35:33,430] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 00:35:33,430] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 00:36:01,174] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 00:36:01,174] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 00:36:22,842] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 00:36:23,962] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 00:41:34,164] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 00:41:35,063] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 00:41:45,435] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 01:02:55,234] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-06 01:08:12,353] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-06 01:44:31,633] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 01:48:06,958] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 01:48:07,916] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 01:48:10,265] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 01:48:10,265] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 01:48:13,545] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 01:48:13,546] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 01:48:15,193] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 01:48:16,478] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 01:49:26,345] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 01:49:26,346] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 01:50:02,938] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 01:50:02,938] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 01:50:12,452] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 01:50:13,783] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 01:59:12,800] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 01:59:13,823] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 01:59:24,920] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 02:21:42,588] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-06 02:31:00,128] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-06 03:06:44,613] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 03:08:53,520] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 03:08:54,349] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 03:08:56,213] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 03:08:56,213] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 03:08:58,098] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 03:08:58,098] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 03:09:00,339] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 03:09:01,319] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 03:09:54,611] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 03:09:54,612] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 03:10:19,635] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 03:10:19,636] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 03:10:27,865] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 03:10:28,901] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 03:15:38,447] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 03:15:39,202] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 03:15:45,898] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 04:07:05,434] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 04:09:21,744] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 04:09:22,803] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 04:09:26,845] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 04:09:26,845] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 04:09:30,305] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 04:09:30,305] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 04:09:33,800] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 04:09:35,182] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 04:10:45,722] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 04:10:45,723] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 04:11:21,448] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 04:11:21,448] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 04:11:35,424] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 04:11:36,814] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 04:16:56,736] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 04:16:57,608] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 04:17:07,767] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 05:11:32,012] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-06 05:17:17,854] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-06 06:15:55,433] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-06 06:21:06,876] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-06 07:04:06,067] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 07:06:18,674] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 07:06:19,445] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 07:06:22,402] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 07:06:22,402] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 07:06:24,378] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 07:06:24,378] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 07:06:25,990] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 07:06:26,871] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 07:07:23,245] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 07:07:23,245] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 07:07:44,076] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 07:07:44,077] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 07:07:52,559] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 07:07:53,483] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 07:13:04,935] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 07:13:05,614] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 07:13:14,384] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 08:07:26,050] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 08:11:01,601] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 08:11:02,651] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 08:11:05,786] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 08:11:05,786] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 08:11:07,911] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 08:11:07,911] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 08:11:09,429] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 08:11:10,527] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 08:12:12,999] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 08:12:13,000] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 08:12:37,428] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 08:12:37,428] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 08:12:46,965] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 08:12:48,118] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 08:21:32,638] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 08:21:33,480] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 08:21:45,145] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 09:11:27,026] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-06 09:16:22,164] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-06 10:04:58,669] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 10:07:05,630] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 10:07:06,394] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 10:07:09,152] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 10:07:09,152] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 10:07:11,070] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 10:07:11,070] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 10:07:12,969] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 10:07:13,925] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 10:08:11,009] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 10:08:11,010] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 10:08:33,374] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 10:08:33,374] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 10:08:45,156] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 10:08:46,190] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 10:14:02,941] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 10:14:03,708] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 10:14:14,738] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 11:03:39,595] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 11:05:47,656] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 11:05:48,380] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 11:05:50,701] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 11:05:50,702] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 11:05:52,824] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 11:05:52,824] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 11:05:53,883] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 11:05:54,845] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 11:06:53,890] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 11:06:53,890] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 11:07:16,926] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 11:07:16,926] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 11:07:26,647] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 11:07:27,663] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 11:12:40,578] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 11:12:41,309] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 11:12:51,500] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 12:09:40,640] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 12:11:50,856] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 12:11:51,728] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 12:11:54,755] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 12:11:54,755] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 12:11:57,252] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 12:11:57,253] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 12:11:59,694] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 12:12:00,771] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 12:12:58,230] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 12:12:58,230] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 12:13:24,009] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 12:13:24,009] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 12:13:39,020] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 12:13:40,147] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 12:18:51,122] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 12:18:51,955] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 12:18:58,666] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 12:22:43,182] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-06 12:31:45,516] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-06 13:05:42,753] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 13:07:57,582] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 13:07:58,347] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 13:08:00,785] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 13:08:00,785] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 13:08:02,862] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 13:08:02,862] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 13:08:04,246] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 13:08:05,133] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 13:09:07,655] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 13:09:07,656] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 13:09:29,309] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 13:09:29,309] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 13:09:49,059] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 13:09:49,994] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 13:15:09,349] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 13:15:10,015] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 13:15:15,179] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 14:03:13,942] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 14:05:28,172] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 14:05:29,005] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 14:05:31,995] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 14:05:31,995] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 14:05:36,189] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 14:05:36,189] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 14:05:38,135] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 14:05:39,138] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 14:06:38,340] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 14:06:38,341] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 14:07:00,621] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 14:07:00,621] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 14:07:25,786] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 14:07:26,851] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 14:12:51,534] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 14:12:52,284] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 14:13:03,157] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 15:12:18,992] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-06 15:17:38,959] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-06 16:16:23,244] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-06 16:21:51,596] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-06 17:03:03,735] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 17:05:18,312] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 17:05:19,020] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 17:05:22,791] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 17:05:22,792] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 17:05:25,644] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 17:05:25,644] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 17:05:27,919] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 17:05:28,881] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 17:06:25,382] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 17:06:25,383] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 17:06:47,386] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 17:06:47,386] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 17:07:01,689] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 17:07:02,693] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 17:12:17,479] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 17:12:18,226] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 17:12:30,676] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 18:14:25,601] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-06 18:20:31,996] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-06 19:09:34,110] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-06 19:14:22,662] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-06 20:04:44,471] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 20:07:00,728] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 20:07:01,482] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 20:07:04,390] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 20:07:04,390] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 20:07:06,359] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 20:07:06,359] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 20:07:09,146] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 20:07:10,103] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 20:08:08,079] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 20:08:08,079] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 20:08:31,977] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 20:08:31,977] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 20:08:42,275] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 20:08:43,287] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 20:14:13,649] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 20:14:14,369] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 20:14:25,080] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 21:03:25,347] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 21:05:53,335] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 21:05:53,979] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 21:05:57,923] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 21:05:57,923] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 21:06:00,361] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 21:06:00,361] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 21:06:06,721] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 21:06:07,601] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 21:07:11,320] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 21:07:11,320] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 21:07:39,922] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 21:07:39,923] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 21:07:56,578] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 21:07:57,491] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 21:13:57,671] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 21:13:58,309] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 21:14:10,518] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 22:04:49,174] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 22:07:15,738] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 22:07:16,576] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 22:07:20,437] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 22:07:20,437] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 22:07:23,982] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 22:07:23,982] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 22:07:26,651] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 22:07:27,724] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 22:08:34,653] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 22:08:34,654] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 22:09:02,896] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 22:09:02,896] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 22:09:19,906] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 22:09:21,034] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 22:15:21,644] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 22:15:22,461] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 22:15:36,424] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-06 23:04:03,083] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-06 23:06:26,339] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-06 23:06:27,095] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-06 23:06:29,669] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-06 23:06:29,670] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-06 23:06:31,724] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-06 23:06:31,724] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-06 23:06:34,011] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-06 23:06:34,967] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-06 23:07:35,752] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-06 23:07:35,752] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-06 23:07:59,158] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-06 23:07:59,158] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-06 23:08:21,848] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-06 23:08:22,851] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-06 23:13:48,453] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-06 23:13:49,220] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-06 23:13:57,955] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 00:35:47,010] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 00:37:48,561] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 00:37:49,452] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 00:37:52,864] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 00:37:52,864] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 00:37:55,676] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 00:37:55,676] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 00:37:58,438] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 00:37:59,400] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 00:38:59,498] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 00:38:59,499] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 00:39:30,482] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 00:39:30,482] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 00:39:42,813] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 00:39:43,875] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 00:44:38,070] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 00:44:38,771] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 00:44:57,950] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 01:08:17,474] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-07 01:14:03,517] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-07 01:56:09,576] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 01:58:20,660] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 01:58:21,463] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 01:58:23,741] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 01:58:23,741] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 01:58:25,819] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 01:58:25,819] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 01:58:27,933] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 01:58:28,920] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 01:59:23,246] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 01:59:23,246] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 01:59:50,803] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 01:59:50,804] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 02:00:03,220] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 02:00:04,272] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 02:05:29,041] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 02:05:29,819] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 02:05:41,011] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 02:29:11,733] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-07 02:34:15,343] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-07 03:13:21,537] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-07 03:18:37,040] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-07 04:07:38,931] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 04:09:42,287] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 04:09:43,011] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 04:09:46,107] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 04:09:46,107] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 04:09:48,087] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 04:09:48,087] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 04:09:49,973] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 04:09:50,899] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 04:10:44,385] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 04:10:44,385] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 04:11:07,955] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 04:11:07,955] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 04:11:19,485] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 04:11:20,452] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 04:16:51,621] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 04:16:52,302] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 04:17:08,705] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 05:05:56,953] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 05:09:29,826] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 05:09:30,763] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 05:09:35,557] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 05:09:35,557] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 05:09:37,672] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 05:09:37,672] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 05:09:39,523] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 05:09:40,639] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 05:10:43,628] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 05:10:43,628] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 05:11:18,108] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 05:11:18,109] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 05:11:33,333] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 05:11:34,605] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 05:20:35,283] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 05:20:36,212] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 05:20:57,795] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 06:08:39,802] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 06:10:48,203] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 06:10:49,252] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 06:10:53,275] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 06:10:53,276] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 06:10:55,485] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 06:10:55,485] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 06:10:57,385] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 06:10:58,688] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 06:12:03,193] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 06:12:03,193] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 06:12:31,998] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 06:12:31,998] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 06:12:42,663] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 06:12:43,941] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 06:17:58,372] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 06:17:59,369] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 06:18:14,594] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 07:06:00,435] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 07:08:03,768] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 07:08:04,505] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 07:08:08,928] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 07:08:08,928] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 07:08:11,951] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 07:08:11,951] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 07:08:14,012] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 07:08:14,971] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 07:09:11,431] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 07:09:11,431] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 07:09:37,702] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 07:09:37,702] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 07:09:49,275] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 07:09:50,287] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 07:14:56,858] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 07:14:57,650] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 07:15:13,632] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 08:08:38,731] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 08:11:04,387] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 08:11:05,082] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 08:11:09,945] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 08:11:09,945] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 08:11:13,353] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 08:11:13,353] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 08:11:15,829] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 08:11:16,736] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 08:12:23,684] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 08:12:23,684] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 08:12:53,249] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 08:12:53,250] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 08:13:06,198] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 08:13:07,136] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 08:19:18,457] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 08:19:19,162] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 08:19:36,410] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 09:06:53,040] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 09:08:50,451] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 09:08:51,176] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 09:08:55,701] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 09:08:55,701] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 09:08:57,906] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 09:08:57,906] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 09:09:00,259] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 09:09:01,151] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 09:10:01,162] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 09:10:01,162] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 09:10:26,527] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 09:10:26,528] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 09:10:46,857] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 09:10:47,794] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 09:15:38,863] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 09:15:39,511] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 09:15:50,968] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 10:06:57,040] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 10:08:58,922] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 10:08:59,757] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 10:09:03,229] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 10:09:03,229] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 10:09:05,325] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 10:09:05,325] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 10:09:07,408] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 10:09:08,347] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 10:10:04,239] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 10:10:04,240] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 10:10:24,917] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 10:10:24,917] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 10:10:47,494] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 10:10:48,482] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 10:15:43,726] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 10:15:44,437] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 10:15:51,418] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 11:03:34,709] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 11:07:13,720] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 11:07:14,617] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 11:07:19,496] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 11:07:19,496] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 11:07:22,690] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 11:07:22,690] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 11:07:24,988] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 11:07:26,129] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 11:08:29,695] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 11:08:29,696] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 11:08:53,419] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 11:08:53,419] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 11:09:11,623] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 11:09:12,793] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 11:18:32,950] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 11:18:33,838] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 11:18:49,986] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 12:11:11,002] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 12:14:51,858] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 12:14:52,686] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 12:14:55,137] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 12:14:55,137] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 12:14:57,059] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 12:14:57,059] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 12:14:58,485] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 12:14:59,468] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 12:15:57,265] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 12:15:57,266] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 12:16:30,062] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 12:16:30,062] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 12:16:38,510] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 12:16:39,640] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 12:25:35,065] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 12:25:35,886] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 12:25:43,978] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 12:26:42,311] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-07 12:34:52,320] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-07 13:16:37,360] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-07 13:22:09,191] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-07 14:12:26,258] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-07 14:18:35,739] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-07 15:06:26,064] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 15:08:52,383] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 15:08:53,252] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 15:08:56,138] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 15:08:56,138] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 15:08:57,990] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 15:08:57,990] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 15:08:59,880] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 15:09:00,858] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 15:09:56,783] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 15:09:56,783] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 15:10:19,155] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 15:10:19,155] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 15:10:34,934] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 15:10:36,035] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 15:16:40,968] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 15:16:41,730] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 15:16:49,347] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 16:16:49,058] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-07 16:22:57,175] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-07 17:04:17,545] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 17:06:42,367] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 17:06:43,295] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 17:06:49,966] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 17:06:49,967] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 17:06:53,928] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 17:06:53,928] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 17:06:55,416] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 17:06:56,705] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 17:08:01,989] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 17:08:01,989] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 17:08:27,282] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 17:08:27,282] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 17:08:39,628] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 17:08:40,846] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 17:15:04,333] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 17:15:05,202] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 17:15:12,263] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 18:07:19,270] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 18:10:02,754] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 18:10:03,609] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 18:10:07,438] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 18:10:07,438] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 18:10:10,270] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 18:10:10,271] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 18:10:12,488] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 18:10:13,467] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 18:11:14,342] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 18:11:14,342] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 18:11:37,656] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 18:11:37,656] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 18:11:52,022] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 18:11:53,055] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 18:18:01,949] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 18:18:02,698] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 18:18:07,826] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 19:03:32,152] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 19:06:05,985] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 19:06:06,743] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 19:06:10,240] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 19:06:10,240] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 19:06:12,676] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 19:06:12,676] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 19:06:15,171] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 19:06:16,069] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 19:07:19,486] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 19:07:19,486] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 19:07:45,680] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 19:07:45,680] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 19:08:03,782] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 19:08:04,825] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 19:14:34,648] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 19:14:35,317] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 19:14:44,637] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 20:06:31,054] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 20:08:48,126] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 20:08:49,005] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 20:08:52,363] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 20:08:52,363] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 20:08:55,963] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 20:08:55,963] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 20:08:58,301] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 20:08:59,431] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 20:10:01,408] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 20:10:01,408] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 20:10:24,210] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 20:10:24,210] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 20:10:34,167] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 20:10:35,386] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 20:15:50,413] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 20:15:51,284] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 20:15:57,462] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 21:04:28,229] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 21:08:21,908] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 21:08:22,868] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 21:08:25,708] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 21:08:25,708] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 21:08:27,511] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 21:08:27,511] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 21:08:29,634] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 21:08:30,864] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 21:09:44,750] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 21:09:44,751] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 21:10:16,993] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 21:10:16,994] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 21:10:27,717] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 21:10:28,958] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 21:20:12,300] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 21:20:13,302] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 21:20:24,389] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 22:04:26,490] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 22:06:59,197] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 22:07:00,064] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 22:07:03,654] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 22:07:03,654] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 22:07:05,908] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 22:07:05,908] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 22:07:08,247] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 22:07:09,206] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 22:08:02,690] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 22:08:02,690] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 22:08:26,730] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 22:08:26,730] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 22:08:41,177] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 22:08:42,206] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 22:14:44,509] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 22:14:45,248] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 22:14:52,029] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-07 23:05:07,238] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-07 23:08:58,998] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-07 23:08:59,803] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-07 23:09:03,031] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-07 23:09:03,031] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-07 23:09:05,358] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-07 23:09:05,358] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-07 23:09:07,361] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-07 23:09:08,386] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-07 23:10:13,752] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-07 23:10:13,752] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-07 23:10:40,255] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-07 23:10:40,256] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-07 23:10:53,568] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-07 23:10:54,631] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-07 23:20:44,361] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-07 23:20:45,125] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-07 23:20:57,229] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-08 00:33:32,696] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-08 00:35:37,623] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-08 00:35:38,746] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-08 00:35:42,592] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-08 00:35:42,593] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-08 00:35:46,074] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-08 00:35:46,074] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-08 00:35:48,594] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-08 00:35:49,862] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-08 00:36:55,497] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-08 00:36:55,498] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-08 00:37:23,443] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-08 00:37:23,443] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-08 00:37:40,769] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-08 00:37:42,021] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-08 00:42:54,024] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-08 00:42:54,989] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-08 00:43:04,718] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-08 01:06:05,221] 	INFO 	39 	fee_data.py 	<module>() 	Fee Data Started
[2023-08-08 01:15:27,353] 	INFO 	139 	fee_data.py 	<module>() 	Fee Data Ended
[2023-08-08 01:54:09,127] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-08 01:56:42,476] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-08 01:56:43,228] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-08 01:56:47,331] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-08 01:56:47,331] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-08 01:56:51,165] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-08 01:56:51,165] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-08 01:56:53,488] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-08 01:56:54,495] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-08 01:57:59,378] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-08 01:57:59,378] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-08 01:58:30,980] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-08 01:58:30,980] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-08 01:58:50,579] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-08 01:58:51,610] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-08 02:05:09,746] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-08 02:05:10,615] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-08 02:05:22,639] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-08 02:23:20,150] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-08 02:25:25,965] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-08 02:25:26,799] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-08 02:25:30,675] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-08 02:25:30,675] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-08 02:25:34,091] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-08 02:25:34,092] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-08 02:25:37,106] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-08 02:25:38,180] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-08 02:26:40,652] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-08 02:26:40,652] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-08 02:27:10,008] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-08 02:27:10,008] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-08 02:27:33,570] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-08 02:27:34,782] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-08 02:32:29,971] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-08 02:32:30,830] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-08 02:32:37,878] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-08 03:06:25,632] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-08 03:08:38,356] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-08 03:08:39,085] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-08 03:08:40,960] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-08 03:08:40,960] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-08 03:08:43,936] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-08 03:08:43,937] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-08 03:08:46,427] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-08 03:08:47,388] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-08 03:09:46,868] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-08 03:09:46,868] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-08 03:10:13,903] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-08 03:10:13,904] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-08 03:10:29,115] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-08 03:10:30,216] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-08 03:16:03,758] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-08 03:16:04,510] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-08 03:16:09,601] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-08 04:07:38,773] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-08 04:09:53,110] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-08 04:09:54,200] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-08 04:09:57,877] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-08 04:09:57,877] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-08 04:10:01,456] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-08 04:10:01,456] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-08 04:10:04,588] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-08 04:10:05,723] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-08 04:11:11,699] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-08 04:11:11,699] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-08 04:11:42,840] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-08 04:11:42,840] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-08 04:11:52,947] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-08 04:11:54,167] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-08 04:17:05,388] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-08 04:17:06,327] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-08 04:17:17,308] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-08-08 05:04:52,953] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-08-08 05:06:52,151] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-08-08 05:06:52,931] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-08-08 05:06:54,935] 	INFO 	73 	day_data.py 	<module>() 	Day Data Ended
[2023-08-08 05:06:54,935] 	INFO 	79 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-08-08 05:06:57,117] 	INFO 	126 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-08-08 05:06:57,117] 	INFO 	133 	day_data.py 	<module>() 	Day Data Combined Started
[2023-08-08 05:06:58,839] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-08-08 05:06:59,782] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-08-08 05:07:54,478] 	ERROR 	112 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Error: 'bool' object is not callable
Traceback (most recent call last):
  File "pair_data.py", line 87, in <module>
    if pairdata_df.empty():
TypeError: 'bool' object is not callable
[2023-08-08 05:07:54,479] 	INFO 	126 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-08-08 05:08:21,442] 	INFO 	193 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-08-08 05:08:21,442] 	INFO 	200 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-08-08 05:08:31,984] 	INFO 	230 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-08-08 05:08:32,978] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-08-08 05:13:56,192] 	INFO 	150 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-08-08 05:13:56,931] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-08-08 05:14:06,503] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
