[2023-02-06 09:41:07,959] 	INFO 	27 	day_data.py 	<module>() 	Process Started
[2023-02-06 09:41:08,166] 	ERROR 	67 	day_data.py 	<module>() 	Error occurred during the process. Error: 'str' object has no attribute 'keys'
[2023-02-06 10:00:48,896] 	INFO 	26 	day_data.py 	<module>() 	Process Started
[2023-02-06 10:00:49,104] 	ERROR 	63 	day_data.py 	<module>() 	Error occurred during the process. Error: '_Environ' object is not callable
[2023-02-06 10:02:59,632] 	INFO 	26 	day_data.py 	<module>() 	Process Started
[2023-02-06 10:02:59,841] 	ERROR 	63 	day_data.py 	<module>() 	Error occurred during the process. Error: 'GKey'
[2023-02-06 10:05:04,002] 	INFO 	26 	day_data.py 	<module>() 	Process Started
[2023-02-06 10:05:06,349] 	INFO 	61 	day_data.py 	<module>() 	Process Ended
